[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/chat"
  to = "https://caremate-ai-backend-ts67450.replit.app/chat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
